version: '3.7'

services:
  meetjs-client:
    container_name: meetjs-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:80