version: "3.2"
services:
  mongo-database:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks: 
        - meetjs

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      DB_URL: mongo-database
      DB_PORT: 27017
      PORT: 9000
      HOST_URL: localhost
    networks:
      - meetjs
    depends_on:
      - mongo-database

volumes:
    mongodb_data_container:

networks: 
    meetjs:
        driver: bridge
